import {
    LABEL_FOR_TEST_AUTHORITY_STATUS,
    LABEL_FOR_TEST_AUTHORITY_UPDATED_FIELD,
    LABEL_FOR_TEST_AUTHORITY_EMAIL_ADDRESS,
    NAME_FOR_TEST_AUTHORITY_EMAIL_FIELD,
    NAME_FOR_TEST_AUTHORITY_ID_FIELD,
    NAME_FOR_TEST_AUTHORITY_NAME_FIELD,
    NAME_FOR_TEST_AUTHORITY_STATUS_FIELD,
    NAME_FOR_TEST_AUTHORITY_UPDATED_FIELD,
    SHORT_LABEL_FOR_TEST_AUTHORITY_ID,
    SHORT_LABEL_FOR_TEST_AUTHORITY_NAME,
} from '../../testAuthorityConstants';

export const TA_ACCOUNT_ADMINISTRATION_TABLE_COLUMNS = [
    {
        Header: LABEL_FOR_TEST_AUTHORITY_UPDATED_FIELD,
        accessor: NAME_FOR_TEST_AUTHORITY_UPDATED_FIELD,
    },
    {
        Header: SHORT_LABEL_FOR_TEST_AUTHORITY_NAME,
        accessor: NAME_FOR_TEST_AUTHORITY_NAME_FIELD,
    },
    {
        Header: SHORT_LABEL_FOR_TEST_AUTHORITY_ID,
        accessor: NAME_FOR_TEST_AUTHORITY_ID_FIELD,
    },
    {
        Header: LABEL_FOR_TEST_AUTHORITY_EMAIL_ADDRESS,
        accessor: NAME_FOR_TEST_AUTHORITY_EMAIL_FIELD,
    },
    {
        Header: LABEL_FOR_TEST_AUTHORITY_STATUS,
        accessor: NAME_FOR_TEST_AUTHORITY_STATUS_FIELD,
    },
];

export const ITEMS_PER_PAGE = 8;

export const TEXT_FOR_FILTER_BY = 'Filter by';
export const LABEL_FOR_FILTERS = 'All';
export const LABEL_FOR_ACTIVE_STATUS_FILTER = 'Active';
export const LABEL_FOR_INACTIVE_STATUS_FILTER = 'Inactive';

export const DISPLAY_FORMAT_FOR_UPDATED_DATE = 'M.d.yyyy';

export const TABLE_SCOPES = {
    [LABEL_FOR_TEST_AUTHORITY_UPDATED_FIELD]: 'row',
};
